spring.application.name=Field
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fieldserviceapp
spring.datasource.username=postgres
spring.datasource.password=Prateek@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

#jwt-secret
jwt.secret=mySuperSecretKeyForJWTAuthentication123456789
jwt.expiration=900000